#extent.properties
extent.reporter.spark.start=true
extent.reporter.spark.out=Report/CucumberExtentReport.html


screenshot.dir=screenshots/
screenshot.rel.path=../screenshots/

basefolder.name=test-output/SparkReport
basefolder.datetimepattern=d-MM-YY HH-mm-ss

document.title=OpenCart Test Report
report.name=Functional Test Execution Summary

extent.reporter.spark.theme=dark

# Report Theme: standard / dark
theme=standard

# Environment Information
system.environment=QA
system.user=Santhosh Kumaran
system.os=Windows 11
system.browser=Chrome